// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurityQuestions.Data;

#nullable disable

namespace SecurityQuestions.Data.Migrations
{
    [DbContext(typeof(QuestionContext))]
    [Migration("20230517034053_SeedQuestions")]
    partial class SeedQuestions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("SecurityQuestions.Models.SecurityQuestion", b =>
                {
                    b.Property<int>("SecurityQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("SecurityQuestionId");

                    b.ToTable("SecurityQuestions");

                    b.HasData(
                        new
                        {
                            SecurityQuestionId = 1,
                            QuestionText = "In what city were you born?"
                        },
                        new
                        {
                            SecurityQuestionId = 2,
                            QuestionText = "What is the name of your favorite pet?"
                        },
                        new
                        {
                            SecurityQuestionId = 3,
                            QuestionText = "What is your mother's maiden name?"
                        },
                        new
                        {
                            SecurityQuestionId = 4,
                            QuestionText = "What high school did you attend?"
                        },
                        new
                        {
                            SecurityQuestionId = 5,
                            QuestionText = "What was the mascot of your high school?"
                        },
                        new
                        {
                            SecurityQuestionId = 6,
                            QuestionText = "What was the make of your first car?"
                        },
                        new
                        {
                            SecurityQuestionId = 7,
                            QuestionText = "What was your favorite toy as a child?"
                        },
                        new
                        {
                            SecurityQuestionId = 8,
                            QuestionText = "Where did you meet your spouse?"
                        },
                        new
                        {
                            SecurityQuestionId = 9,
                            QuestionText = "What is your favorite meal?"
                        },
                        new
                        {
                            SecurityQuestionId = 10,
                            QuestionText = "What is the first name of the best man at your wedding?"
                        });
                });

            modelBuilder.Entity("SecurityQuestions.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SecurityQuestions.Models.UserQuestion", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecurityQuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Answer")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "SecurityQuestionId");

                    b.HasIndex("SecurityQuestionId");

                    b.ToTable("UserQuestion");
                });

            modelBuilder.Entity("SecurityQuestions.Models.UserQuestion", b =>
                {
                    b.HasOne("SecurityQuestions.Models.SecurityQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("SecurityQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurityQuestions.Models.User", null)
                        .WithMany("Questions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SecurityQuestions.Models.User", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
